services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=visitasdb
      - POSTGRES_USER=guto
      - POSTGRES_PASSWORD=senha123
      - DB_HOST=db
    networks:
      - backend-net

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=visitasdb
      - POSTGRES_USER=guto
      - POSTGRES_PASSWORD=senha123
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  db-data:

networks:
  backend-net:
    driver: bridge